

const productos = [
	{
		id : 1,
		nombre : "PRADA Women Edition",
		precio : 12000,
		img: "assets/prada.webp",
		cantidad : 1,
	},
	{
		id : 2,
		nombre : "Perfume LoveSweet",
		precio : 14000,
		img: "assets/perfumelovesweet.webp",
		cantidad : 1,
	},
	{
		id : 3,
		nombre : "Fragancia Gucci",
		precio : 18000,
		img : "assets/perfumemujergucci.webp",
		cantidad : 1,
	},
	{
		id : 4,
		nombre : "Shalimar",
		precio : 29000,
		img: "assets/shalimar.jpg",
		cantidad : 1,
	},
	{
		id : 5,
		nombre : "Roja Oceania Fragancia",
		precio : 29000,
		img: "assets/rojaoceania.webp",
		cantidad : 1,
	},
	{
		id : 6,
		nombre : "Victoria Secret",
		precio : 12000,
		img: "assets/victoria secret.png",
		cantidad : 1,
	},
	{
		id : 7,
		nombre : "Blue Label",
		precio : 29000,
		img: "assets/bluelabel.jpg",
		cantidad : 1,
	},
	{
		id : 8,
		nombre : "Fahrenheit Absolute",
		precio : 14000,
		img: "assets/fahrenheitAbsolute.jpg",
		cantidad : 1,
	},
	{
		id : 9,
		nombre : "White Linen",
		precio : 10000,
		img: "assets/whitelinen.jpg",
		cantidad : 1,
	},
	{
		id : 10,
		nombre : "Aerin Fragances",
		precio : 7000,
		img: "assets/aerin.jpg",
		cantidad : 1,
	},
	{
		id : 11,
		nombre : "Coco Chanel",
		precio : 17000,
		img: "assets/cocochanel.jpg",
		cantidad : 1,
	},
	{
		id : 12,
		nombre : "Sauvage Dior",
		precio : 29000,
		img: "assets/sauvage.jpg",
		cantidad : 1,
	},
];